# This file is automatically generated by the installer.
# Do not edit by hands.

module Alexandria
    module Config
        DATA_DIR = '/usr/local/share/alexandria'
        LIB_DIR = '/usr/local/lib/ruby/site_ruby/1.8'
    end
end
