# This file is automatically generated by the alexandria installer.
# Do not edit it directly.

module Alexandria
  class Preferences
    DEFAULT_VALUES = {
      "position" => [0, 0],
      "size" => [640, 480],
      "maximized" => false,
      "sidepane_position" => 140,
      "view_as" => 0,
      "arrange_icons_mode" => 0,
      "reverse_icons" => false,
      "barcode_scanner" => "CueCat",
      "play_scanning_sound" => true,
      "play_scan_sound" => true,
      "toolbar_visible" => true,
      "sidepane_visible" => true,
      "statusbar_visible" => true,
      "col_authors_visible" => true,
      "col_edition_visible" => true,
      "col_isbn_visible" => true,
      "col_publisher_visible" => true,
      "col_publish_date_visible" => true,
      "col_loaned_to_visible" => true,
      "col_rating_visible" => true,
      "col_redd_visible" => true,
      "col_own_visible" => true,
      "col_want_visible" => true,
      "col_tags_visible" => true,
      "cols_width" => "{}",
      "providers_priority" => ["Amazon", "BarnesAndNoble", "AdLibris", "Proxis", "Thalia", "Siciliano", "WorldCat", "LOC", "BL", "SBN"],
      "view_advanced_settings" => false
    }
  end
end
